name: Build Typst document

on:
  push:
    branches:
      - sources

jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: sources

      - name: Debug Directory Contents
        run: |
          ls -R

      - name: Build Typst documents
        run: |
          docker run -e "XDG_CACHE_HOME=/root" --user $(id -u):$(id -g) -v ${{ github.workspace }}:/root --rm ghcr.io/typst/typst:latest find documentazione -type f -name "*\.typ" -exec sh -c 'typst compile --root . "$1" && rm -rf typst/packages/preview/' _ {} \;

      - name: Commit and push PDF files to approval branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          # Add and commit PDF files to the sources branch
          git add documentazione/RTB/**/*.pdf
          git commit -m "Update PDF files [skip ci]"
          git status
          git fetch
          git status
          # Create and switch to the approval branch
          git checkout approval
          
          git rm -r documentazione
          git commit -m "Delete old existing documents [skip ci]"
          git push origin approval

          # Check out PDF files from the sources branch
          git checkout sources -- documentazione/RTB/**/*.pdf
      
          # Add, commit, and push changes to the documents branch
          git add .
          git commit -m "Update PDF files [skip ci]"
          git push origin approval
